# Generated by Django 4.1.3 on 2023-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subclaim",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
