# Generated by Django 4.1.3 on 2023-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_subclaim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subclaim",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
