# Generated by Django 4.1.3 on 2022-11-02 19:41

import charidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=charidfield.fields.CharIDField(
                default="roPJhNyzQ5auoSviBmVCR",
                help_text="nanoid-format identifier for this entity.",
                max_length=30,
                prefix="",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
